# Generated by Django 3.1 on 2021-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Subtitle', models.CharField(max_length=400)),
                ('Post', models.CharField(max_length=5000)),
                ('Date', models.DateField()),
                ('Author', models.CharField(max_length=100)),
            ],
        ),
    ]
