# Generated by Django 3.1 on 2021-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=5000)),
            ],
        ),
    ]
