# Generated by Django 3.1 on 2021-03-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
